spring:
  application:
    name: Backwoods CRM API
  datasource:
    url: jdbc:mysql://localhost:3306/backwoods_crm_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: true
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: backwoodslabs39@gmail.com
    password: k1t5ijGRFz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "YOUR_SECRET_KEY"
  expiration: 3600000

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController: DEBUG
    org.springframework: ERROR

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
